name: Gatsby Build & Deploy

on:
  push:
  repository_dispatch:
    types:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check Npm Cache
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
             
      - name: Check Gatsby Cache
        uses: actions/cache@v2
        id: gatsby-cache-folder
        with:
          path: .cache
          key: ${{ runner.os }}-cache-site
          restore-keys: |
            ${{ runner.os }}-cache-site

      - name: Check Gatsby Public Folder
        uses: actions/cache@v2
        id: gatsby-public-folder
        with:
          path: public/
          key: ${{ runner.os }}-public-site
          restore-keys: |
            ${{ runner.os }}-public-site

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
          
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli
      
      - name: Build
        run: gatsby build --log-pages
        env:
          NODE_ENV: production
          ENVIRONMENT: ${{ contains(github.ref, 'main') && 'production' || 'staging'}}
          GATSBY_WP_GRAPH_API: ${{ secrets.GATSBY_WP_GRAPH_API }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: public
